name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          echo "==> Current directory contents:"
          ls -R
          echo "==> Installing from starter/requirements.txt"
          pip install -r starter/requirements.txt
          pip install flake8 pytest

      - name: Run tests with pytest
        run: pytest

      